[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\x11/home/navrajkalsi)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\0\0\0\0\0\0\0\a\x7f\0\0\x4\x37\0\0\0\0\0\0\0\0\0\0\a\x7f\0\0\x4\x37\0\0\0\0\0\0\0\0\a\x80\0\0\0\0\0\0\0\0\0\0\a\x7f\0\0\x4\x37)

[FullScreen]
pos=@Point(566 1003)
screen=@Rect(0 0 1920 1080)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(937 918)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[Mediainfo]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\xe\0\0\0\xe\0\0\x3\xb6\0\0\x1\xff\0\0\0\xe\0\0\0\xe\0\0\x3\xb6\0\0\x1\xff\0\0\0\0\0\0\0\0\a\x80\0\0\0\xe\0\0\0\xe\0\0\x3\xb6\0\0\x1\xff)

[RecentsMRL]
list=file:///home/navrajkalsi/downloads/demo-ezgif.com-resize-video.mp4, file:///home/navrajkalsi/projects/proxy-c/v2/media/demo.mp4, file:///home/navrajkalsi/projects/gsim-rs/media/demo.mkv, file:///home/navrajkalsi/Downloads/recording.mkv, file:///home/navrajkalsi/done.mkv, file:///home/navrajkalsi/recording.mkv, file:///home/navrajkalsi/Downloads/Project.Hail.Mary.2026.1080p.WEB-DL.x265.6CH-Pahe.in.mkv, file:///home/navrajkalsi/projects/gsim-rs/media/demo.mp4, file:///home/navrajkalsi/demo.mkv, file:///home/navrajkalsi/Downloads/demo%20%28online-video-cutter.com%29.mp4, file:///home/navrajkalsi/out.mkv, file:///home/navrajkalsi/Downloads/recording-ezgif.com-video-cutter.mkv, file:///home/navrajkalsi/Downloads/demo.mp4, file:///mnt/files/Movies/Dune/Dune%20Part%202.mkv, file:///mnt/files/Movies/Dune/Dune%20Part%201.mkv
times=4400, 0, 0, 0, 0, 6272, 0, 9900, 0, 0, 0, 32336, 0, 0, 8204681
