[General]
filedialog-path=@Variant(\0\0\0\x11\0\0\0\x11/home/navrajkalsi)
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\0\xe\0\0\0\xe\0\0\x3\xb6\0\0\x4\x2\0\0\0\xe\0\0\0\xe\0\0\x3\xb6\0\0\x4\x2\0\0\0\0\0\0\0\0\a\x80\0\0\0\xe\0\0\0\xe\0\0\x3\xb6\0\0\x4\x2)

[FullScreen]
pos=@Point(565 1015)
screen=@Rect(0 0 1920 1080)
wide=false

[MainWindow]
adv-controls=0
bgSize=@Size(937 941)
pl-dock-status=true
playlist-visible=false
playlistSize=@Size(-1 -1)
status-bar-visible=false

[Mediainfo]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x3\xc9\0\0\0\xe\0\0\aq\0\0\x1\xff\0\0\x3\xc9\0\0\0\xe\0\0\aq\0\0\x1\xff\0\0\0\0\0\0\0\0\a\x80\0\0\x3\xc9\0\0\0\xe\0\0\aq\0\0\x1\xff)

[RecentsMRL]
list=file:///home/navrajkalsi/downloads/Batman.v.Superman.Dawn.of.Justice.2016.IMAX.Utimate.Edition.1080p.WEB-DL.x265.DD%2B5.1-Pahe.in.mkv, file:///home/navrajkalsi/downloads/Dune%20Part%203%20Trailer.mp4, file:///home/navrajkalsi/downloads/DUNE%20PART%20THREE%20%282026%29%20-%20Official%20IMAX%C2%AE%20%281.90%29%20Trailer%20%5B4K%20Ultra%20HD%5D.mkv, file:///mnt/files/Movies/Dune/Dune%20Part%202.mkv, file:///mnt/files/Movies/Christopher%20Nolan/Oppenheimer.mkv, file:///mnt/files/Movies/Dune/Dune%20Part%201.mkv, file:///mnt/files/Movies/Project%20Hail%20Mary.mkv, file:///mnt/files/Movies/Collateral.mkv, file:///mnt/files/The%20Odyssey%201.85.mkv, file:///home/navrajkalsi/downloads/YTDown.com_YouTube_Dune-Part-Three-Official-Trailer_Media_NdvqHc56lE0_001_1080p.mp4, file:///mnt/files/Movies/F1.mkv, file:///mnt/files/Movies/Deadpool%20and%20Wolverine.mkv, file:///mnt/files/Movies/Christopher%20Nolan/Batman/The%20Dark%20Knight%20Rises.mkv, file:///mnt/files/Movies/Christopher%20Nolan/Batman/The%20Dark%20Knight.mkv, file:///mnt/files/Movies/Mission%20Impossible/Mission%20Impossible%20-%20The%20Final%20Reckoning.mkv, file:///mnt/files/Movies/A%20House%20of%20Dynamite.mkv, file:///home/navrajkalsi/downloads/Gravity.2013.Silent.Space.1080p.BluRay.x264.DD5.1-Pahe.in.mkv, file:///mnt/files/Movies/The%20Smashing%20Machine.mkv, file:///run/media/navrajkalsi/ESD-USB/Dune%20Part%202.mkv, file:///mnt/files/Movies/Anora.mkv, file:///home/navrajkalsi/downloads/demo-ezgif.com-resize-video.mp4, file:///home/navrajkalsi/projects/proxy-c/v2/media/demo.mp4, file:///home/navrajkalsi/projects/gsim-rs/media/demo.mkv, file:///home/navrajkalsi/Downloads/recording.mkv, file:///home/navrajkalsi/done.mkv, file:///home/navrajkalsi/recording.mkv, file:///home/navrajkalsi/Downloads/Project.Hail.Mary.2026.1080p.WEB-DL.x265.6CH-Pahe.in.mkv, file:///home/navrajkalsi/projects/gsim-rs/media/demo.mp4, file:///home/navrajkalsi/demo.mkv, file:///home/navrajkalsi/Downloads/demo%20%28online-video-cutter.com%29.mp4
times=0, 49407, 11274, 0, 0, 0, 8353567, 0, 0, 0, 0, 0, 8205431, 7171273, 9851576, 682486, 2886742, 3234048, 8083943, 0, 4400, 0, 0, 0, 0, 6272, 0, 9900, 0, 0
