general {
    hide_cursor = true
    ignore_empty_input = true
}

animations {
    enabled = false
}

background {
    path = $HOME/.dotfiles/wallpaper2.jpg
    blur_passes = 0
}

input-field {
    size = 10%, 5%
    outline_thickness = 0
    dots_size = 0.3
    dots_spacing = 0.5

    inner_color = rgba(00000000)
    font_color = rgba(ffffffaf)
    placeholder_text =
    check_color = rgba(000000ff)
    fail_color = rgba(ff000077)
    fail_text =

    position = 0, -444
}

# label {
#     text = $TIME
#     color = rgba(000000aa)
#     font_size = 100
#
#     position = -30, 0
#     halign = right
#     valign = top
# }
